job:
  script:
    - mkdir -p /var/www/classes/863.24/people/KyeShimizu
    - export GIT_WORK_TREE=/var/www/classes/863.24/people/KyeShimizu/
    - git checkout -f main
    - git reset --hard origin/main
    - git pull
    - wget -qO- https://get.pnpm.io/install.sh | sh -
    - source /home/gitlab-runner/.bashrc
    - pnpm ci
    - pnpm run build
    - cp -rf /var/www/classes/863.24/people/KyeShimizu/public/* /var/www/classes/863.24/people/KyeShimizu/public/
