M48
; DRILL file {KiCad 8.0.5} date 2024-10-14T16:25:52-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-14T16:25:52-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.140
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.400
%
G90
G05
T1
X157.0Y-95.74
T2
X157.0Y-93.2
T3
X171.0Y-92.0
X171.0Y-97.0
M30
