M48
; DRILL file {KiCad 8.0.6} date 2024-11-01T18:25:12-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-01T18:25:12-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.140
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C3.100
%
G90
G05
T1
X138.0Y-75.0
T2
X142.0Y-81.38
X142.0Y-83.92
X142.0Y-86.46
X142.0Y-89.0
T3
X131.5Y-69.0
X131.5Y-98.0
M30
